# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/152-hoPF7F2telsjjlcKYqespvr50OR-X
"""

tasks = []

def add_task():
    task = input("Enter a task: ")
    tasks.append(task)
    print(f"Task '{task}' has been added to the list.")

def show_tasks():
    if not tasks:
        print("No tasks in the list.")
    else:
        print("Tasks in the list:")
        for index, task in enumerate(tasks, start=1):
            print(f"{index}. {task}")


def remove_task():
    show_tasks()
    try:
        task_index = int(input("Enter the index of the task to remove: ")) - 1
        if 0 <= task_index < len(tasks):
            removed_task = tasks.pop(task_index)
            print(f"Task '{removed_task}' has been removed from the list.")
        else:
            print("Invalid index. No task removed.")
    except ValueError:
        print("Invalid input. Please enter a valid index.")


while True:
    print("\nOptions:")
    print("1. Add Task")
    print("2. Show Tasks")
    print("3. Remove Task")
    print("4. Quit")

    choice = input("Enter your choice (1/2/3/4): ")

    if choice == '1':
        add_task()
    elif choice == '2':
        show_tasks()
    elif choice == '3':
        remove_task()
    elif choice == '4':
        print("Goodbye!")
        break
    else:
        print("Invalid choice. Please choose a valid option.")